
FUNCTION_DEF = 'FUNCTION_DEF'
FUNCTION_NAME = 'FUNCTION_NAME'
RETURN_TYPE = 'RETURN_TYPE'

PARAMETER_LIST = 'PARAMETER_LIST'
PARAMETER_DECL = 'PARAMETER_DECL'
NAME = 'NAME'

CTOR_LIST = 'CTOR_LIST'
CTOR_INITIALIZER = 'CTOR_INITIALIZER'
INITIALIZER_ID = 'INITIALIZER_ID'

CLASS_DEF = 'CLASS_DEF'
CLASS_NAME = 'CLASS_NAME'
CTOR_EXPR = 'CTOR_EXPR'
BASE_CLASSES = 'BASE_CLASSES'
CLASS_CONTENT = 'CLASS_CONTENT'

TYPE_DEF = 'TYPE_DEF'
TYPE_NAME = 'TYPE_NAME'
TYPE = 'TYPE'
INIT_DECL_LIST = 'INIT_DECL_LIST'

STATEMENTS = 'STATEMENTS'

SELECTION = 'SELECTION'
ITERATION = 'ITERATION'
KEYWORD = 'KEYWORD'

CONDITION = 'CONDITION'  
FOR_INIT = 'FOR_INIT'
FOR_EXPR = 'FOR_EXPR'


FUNCTION_CALL = 'FUNCTION_CALL'
UNARY_EXPR = 'UNARY_EXPR'
UNARY_OPERATOR = 'UNARY_OPERATOR'
FIELD = 'FIELD'
CALL_TEMPLATE_LIST = 'CALL_TEMPLATE_LIST'
CALLEE = 'CALLEE'
ARGUMENT = 'ARGUMENT'

SIMPLE_DECL = 'SIMPLE_DECL'

VAR_DECL = 'VAR_DECL'
POINTER = 'POINTER'
TYPE_SUFFIX = 'TYPE_SUFFIX'
INIT = 'INIT'

NAMESPACE_DEF = 'NAMESPACE_DEF'
USING_DIRECTIVE = 'USING_DIRECTIVE'
INCLUDE_DIRECTIVE = 'INCLUDE_DIRECTIVE'
TEMPLATE_DECL_SPECIFIER = 'TEMPLATE_DECL_SPECIFIER'

JUMP_STATEMENT = 'JUMP_STATEMENT'
DESTINATION = 'DESTINATION'
LABEL = 'LABEL'

EXPR_STATEMENT = 'EXPR_STATEMENT'

BIT_OR = 'BIT_OR'
BIT_OR_ELEM = 'BIT_OR_ELEM'
BRACKETS = 'BRACKETS'
CURLIES = 'CURLIES'
SQUARES = 'SQUARES'
AND = 'AND'
OR = 'OR'
COND_EXPR = 'COND_EXPR'
EXPR = 'EXPR'

ASSIGN = 'ASSIGN'
ASSIGN_OP = 'ASSIGN_OP'
LVAL = 'LVAL'
RVAL = 'RVAL'

REL_OPERATOR = 'REL_OPERATOR'
EQ_OPERATOR = 'EQ_OPERATOR'

LEAF_NODE = 'LEAF_NODE'